// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://esxgdzkxifyiclbwcrlg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzeGdkemt4aWZ5aWNsYndjcmxnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NDc0NzYsImV4cCI6MjA2NzEyMzQ3Nn0.4HOD_77DrZ23T1kQDxxOqqf_tQ-5l2wHh2JIJY2Wghk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});